"""canonical source links on work

Revision ID: 235993d2e507
Revises: 5006e52258a1
Create Date: 2026-09-03 07:13:19.032324
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '235993d2e507'
down_revision = '5006e52258a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('musicbrainz_id', sa.String(length=64), nullable=True))
    op.add_column('work', sa.Column('imslp_title', sa.Text(), nullable=True))
    op.add_column('work', sa.Column('imslp_url', sa.Text(), nullable=True))
    op.add_column('work', sa.Column('wikidata_id', sa.String(length=24), nullable=True))
    op.add_column('work', sa.Column('match_note', sa.Text(), nullable=True))
    op.add_column('work', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    # The table may already hold rows, so the flag arrives with a default and
    # only then becomes NOT NULL.
    op.add_column(
        'work',
        sa.Column('confirmed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('work', 'confirmed', server_default=None)
    op.create_index(op.f('ix_work_musicbrainz_id'), 'work', ['musicbrainz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_musicbrainz_id'), table_name='work')
    op.drop_column('work', 'confirmed')
    op.drop_column('work', 'enriched_at')
    op.drop_column('work', 'match_note')
    op.drop_column('work', 'wikidata_id')
    op.drop_column('work', 'imslp_url')
    op.drop_column('work', 'imslp_title')
    op.drop_column('work', 'musicbrainz_id')
    # ### end Alembic commands ###
