"""annotations belong to the file, not the piece

Revision ID: ce692cf7da23
Revises: 0ae3f2f26723
Create Date: 2026-09-05 10:38:34.903551
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ce692cf7da23'
down_revision = '0ae3f2f26723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Added nullable so existing rows can be carried across, then tightened.
    op.add_column('annotation', sa.Column('source_file_id', sa.Integer(), nullable=True))

    # The ink moves with its page, not with the piece that happened to claim
    # it: the file page is the piece's start plus the offset within it.
    op.execute("""
        UPDATE annotation AS a
           SET source_file_id = p.source_file_id,
               page = a.page + p.page_start - 1
          FROM piece AS p
         WHERE p.id = a.piece_id
    """)
    # A row whose piece has already gone has nothing to be attached to; the
    # cascade would have taken it anyway.
    op.execute("DELETE FROM annotation WHERE source_file_id IS NULL")
    op.alter_column('annotation', 'source_file_id', nullable=False)

    op.drop_index(op.f('ix_annotation_piece_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_piece_page'), table_name='annotation')
    op.drop_constraint(op.f('uq_annotation_page'), 'annotation', type_='unique')
    op.create_unique_constraint('uq_annotation_page', 'annotation', ['source_file_id', 'user_id', 'page'], postgresql_nulls_not_distinct=True)
    op.create_index('ix_annotation_file_page', 'annotation', ['source_file_id', 'page'], unique=False)
    op.create_index(op.f('ix_annotation_source_file_id'), 'annotation', ['source_file_id'], unique=False)
    op.drop_constraint(op.f('annotation_piece_id_fkey'), 'annotation', type_='foreignkey')
    op.create_foreign_key(None, 'annotation', 'source_file', ['source_file_id'], ['id'], ondelete='CASCADE')
    op.drop_column('annotation', 'piece_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Not reversible without loss.

    Going back means choosing a piece for each mark, and a mark on a page no
    piece currently claims has no answer.  Restore from a dump instead.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('piece_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'annotation', type_='foreignkey')
    op.create_foreign_key(op.f('annotation_piece_id_fkey'), 'annotation', 'piece', ['piece_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_annotation_source_file_id'), table_name='annotation')
    op.drop_index('ix_annotation_file_page', table_name='annotation')
    op.drop_constraint('uq_annotation_page', 'annotation', type_='unique')
    op.create_unique_constraint(op.f('uq_annotation_page'), 'annotation', ['piece_id', 'user_id', 'page'], postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_annotation_piece_page'), 'annotation', ['piece_id', 'page'], unique=False)
    op.create_index(op.f('ix_annotation_piece_id'), 'annotation', ['piece_id'], unique=False)
    op.drop_column('annotation', 'source_file_id')
    # ### end Alembic commands ###
