"""composer enrichment fields

Revision ID: 996454b654e9
Revises: c6886ac03564
Create Date: 2026-09-02 20:56:12.562221
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '996454b654e9'
down_revision = 'c6886ac03564'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composer', sa.Column('period', sa.String(length=24), nullable=True))
    op.add_column('composer', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('composer', sa.Column('wikipedia_url', sa.Text(), nullable=True))
    op.add_column('composer', sa.Column('wikidata_id', sa.String(length=24), nullable=True))
    op.add_column('composer', sa.Column('portrait_file', sa.String(length=120), nullable=True))
    op.add_column('composer', sa.Column('portrait_source_url', sa.Text(), nullable=True))
    op.add_column('composer', sa.Column('portrait_credit', sa.Text(), nullable=True))
    op.add_column('composer', sa.Column('portrait_license', sa.String(length=120), nullable=True))
    op.add_column('composer', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_composer_period'), 'composer', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_composer_period'), table_name='composer')
    op.drop_column('composer', 'enriched_at')
    op.drop_column('composer', 'portrait_license')
    op.drop_column('composer', 'portrait_credit')
    op.drop_column('composer', 'portrait_source_url')
    op.drop_column('composer', 'portrait_file')
    op.drop_column('composer', 'wikidata_id')
    op.drop_column('composer', 'wikipedia_url')
    op.drop_column('composer', 'description')
    op.drop_column('composer', 'period')
    # ### end Alembic commands ###
