"""initial catalogue schema

Revision ID: c6886ac03564
Revises: 
Create Date: 2026-09-02 20:13:29.135732
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c6886ac03564'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oidc_subject', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_oidc_subject'), 'app_user', ['oidc_subject'], unique=True)
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('adapter', sa.String(length=40), nullable=False),
    sa.Column('ignore_globs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_accept', sa.Float(), nullable=False),
    sa.Column('review_floor', sa.Float(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_path')
    )
    op.create_index(op.f('ix_collection_name'), 'collection', ['name'], unique=False)
    op.create_table('composer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('sort_name', sa.String(length=200), nullable=False),
    sa.Column('born', sa.Integer(), nullable=True),
    sa.Column('died', sa.Integer(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('musicbrainz_id', sa.String(length=64), nullable=True),
    sa.Column('imslp_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composer_canonical_name'), 'composer', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_composer_sort_name'), 'composer', ['sort_name'], unique=False)
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_name'), 'instrument', ['name'], unique=True)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_claim', 'job', ['state', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_kind'), 'job', ['kind'], unique=False)
    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_token_token_hash'), 'api_token', ['token_hash'], unique=True)
    op.create_table('shelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_name'), 'shelf', ['name'], unique=False)
    op.create_index(op.f('ix_shelf_owner_id'), 'shelf', ['owner_id'], unique=False)
    op.create_table('source_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), nullable=False),
    sa.Column('managed_path', sa.Text(), nullable=True),
    sa.Column('scan_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'rel_path', name='uq_file_path')
    )
    op.create_index('ix_file_hash', 'source_file', ['sha256'], unique=False)
    op.create_index(op.f('ix_source_file_collection_id'), 'source_file', ['collection_id'], unique=False)
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=True),
    sa.Column('parent_work_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('catalog_system', sa.String(length=12), nullable=True),
    sa.Column('catalog_number', sa.Integer(), nullable=True),
    sa.Column('catalog_suffix', sa.String(length=8), nullable=False),
    sa.Column('catalog_sub', sa.Integer(), nullable=True),
    sa.Column('music_key', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('form', sa.String(length=80), nullable=True),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('movement_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_work_id'], ['work.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('composer_id', 'catalog_system', 'catalog_number', 'catalog_suffix', 'catalog_sub', name='uq_work_catalog')
    )
    op.create_index(op.f('ix_work_catalog_number'), 'work', ['catalog_number'], unique=False)
    op.create_index(op.f('ix_work_catalog_system'), 'work', ['catalog_system'], unique=False)
    op.create_index(op.f('ix_work_composer_id'), 'work', ['composer_id'], unique=False)
    op.create_index(op.f('ix_work_form'), 'work', ['form'], unique=False)
    op.create_index(op.f('ix_work_music_key'), 'work', ['music_key'], unique=False)
    op.create_index(op.f('ix_work_parent_work_id'), 'work', ['parent_work_id'], unique=False)
    op.create_index(op.f('ix_work_period'), 'work', ['period'], unique=False)
    op.create_index('ix_work_sort', 'work', ['composer_id', 'catalog_system', 'catalog_number'], unique=False)
    op.create_index(op.f('ix_work_title'), 'work', ['title'], unique=False)
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('printed_first_page', sa.Integer(), nullable=True),
    sa.Column('printed_last_page', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('composer_name', sa.String(length=200), nullable=True),
    sa.Column('catalog_display', sa.String(length=64), nullable=True),
    sa.Column('music_key', sa.String(length=32), nullable=True),
    sa.Column('form', sa.String(length=80), nullable=True),
    sa.Column('arranger', sa.String(length=200), nullable=True),
    sa.Column('edition', sa.String(length=200), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('route', sa.String(length=10), nullable=False),
    sa.Column('review_state', sa.String(length=10), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes_machine', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_opened', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_end >= page_start', name='ck_piece_pages'),
    sa.CheckConstraint('page_start >= 1', name='ck_piece_page_start'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piece_composer_name'), 'piece', ['composer_name'], unique=False)
    op.create_index(op.f('ix_piece_confidence'), 'piece', ['confidence'], unique=False)
    op.create_index('ix_piece_file_pages', 'piece', ['source_file_id', 'page_start'], unique=False)
    op.create_index(op.f('ix_piece_form'), 'piece', ['form'], unique=False)
    op.create_index(op.f('ix_piece_music_key'), 'piece', ['music_key'], unique=False)
    op.create_index(op.f('ix_piece_review_state'), 'piece', ['review_state'], unique=False)
    op.create_index('ix_piece_route', 'piece', ['route', 'confidence'], unique=False)
    op.create_index(op.f('ix_piece_source_file_id'), 'piece', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_piece_status'), 'piece', ['status'], unique=False)
    op.create_index(op.f('ix_piece_title'), 'piece', ['title'], unique=False)
    op.create_index(op.f('ix_piece_work_id'), 'piece', ['work_id'], unique=False)
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_piece_id'), 'annotation', ['piece_id'], unique=False)
    op.create_index('ix_annotation_piece_page', 'annotation', ['piece_id', 'page'], unique=False)
    op.create_table('field_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('piece_id', 'field', 'source', 'value', name='uq_candidate')
    )
    op.create_index('ix_candidate_piece_field', 'field_candidate', ['piece_id', 'field'], unique=False)
    op.create_index(op.f('ix_field_candidate_accepted'), 'field_candidate', ['accepted'], unique=False)
    op.create_index(op.f('ix_field_candidate_piece_id'), 'field_candidate', ['piece_id'], unique=False)
    op.create_table('piece_instrument',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('piece_id', 'instrument_id')
    )
    op.create_table('shelf_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelf.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelf_id', 'piece_id', name='uq_shelf_piece')
    )
    op.create_index(op.f('ix_shelf_item_piece_id'), 'shelf_item', ['piece_id'], unique=False)
    op.create_index(op.f('ix_shelf_item_shelf_id'), 'shelf_item', ['shelf_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelf_item_shelf_id'), table_name='shelf_item')
    op.drop_index(op.f('ix_shelf_item_piece_id'), table_name='shelf_item')
    op.drop_table('shelf_item')
    op.drop_table('piece_instrument')
    op.drop_index(op.f('ix_field_candidate_piece_id'), table_name='field_candidate')
    op.drop_index(op.f('ix_field_candidate_accepted'), table_name='field_candidate')
    op.drop_index('ix_candidate_piece_field', table_name='field_candidate')
    op.drop_table('field_candidate')
    op.drop_index('ix_annotation_piece_page', table_name='annotation')
    op.drop_index(op.f('ix_annotation_piece_id'), table_name='annotation')
    op.drop_table('annotation')
    op.drop_index(op.f('ix_piece_work_id'), table_name='piece')
    op.drop_index(op.f('ix_piece_title'), table_name='piece')
    op.drop_index(op.f('ix_piece_status'), table_name='piece')
    op.drop_index(op.f('ix_piece_source_file_id'), table_name='piece')
    op.drop_index('ix_piece_route', table_name='piece')
    op.drop_index(op.f('ix_piece_review_state'), table_name='piece')
    op.drop_index(op.f('ix_piece_music_key'), table_name='piece')
    op.drop_index(op.f('ix_piece_form'), table_name='piece')
    op.drop_index('ix_piece_file_pages', table_name='piece')
    op.drop_index(op.f('ix_piece_confidence'), table_name='piece')
    op.drop_index(op.f('ix_piece_composer_name'), table_name='piece')
    op.drop_table('piece')
    op.drop_index(op.f('ix_work_title'), table_name='work')
    op.drop_index('ix_work_sort', table_name='work')
    op.drop_index(op.f('ix_work_period'), table_name='work')
    op.drop_index(op.f('ix_work_parent_work_id'), table_name='work')
    op.drop_index(op.f('ix_work_music_key'), table_name='work')
    op.drop_index(op.f('ix_work_form'), table_name='work')
    op.drop_index(op.f('ix_work_composer_id'), table_name='work')
    op.drop_index(op.f('ix_work_catalog_system'), table_name='work')
    op.drop_index(op.f('ix_work_catalog_number'), table_name='work')
    op.drop_table('work')
    op.drop_index(op.f('ix_source_file_collection_id'), table_name='source_file')
    op.drop_index('ix_file_hash', table_name='source_file')
    op.drop_table('source_file')
    op.drop_index(op.f('ix_shelf_owner_id'), table_name='shelf')
    op.drop_index(op.f('ix_shelf_name'), table_name='shelf')
    op.drop_table('shelf')
    op.drop_index(op.f('ix_api_token_token_hash'), table_name='api_token')
    op.drop_table('api_token')
    op.drop_index(op.f('ix_job_kind'), table_name='job')
    op.drop_index('ix_job_claim', table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_instrument_name'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_index(op.f('ix_composer_sort_name'), table_name='composer')
    op.drop_index(op.f('ix_composer_canonical_name'), table_name='composer')
    op.drop_table('composer')
    op.drop_index(op.f('ix_collection_name'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_app_user_oidc_subject'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
