"""instrumentation on the piece row

Revision ID: 0ae3f2f26723
Revises: 0741584327eb
Create Date: 2026-09-03 23:07:14.932836
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0ae3f2f26723'
down_revision = '0741584327eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('instrumentation', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_piece_instrumentation'), 'piece', ['instrumentation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_piece_instrumentation'), table_name='piece')
    op.drop_column('piece', 'instrumentation')
    # ### end Alembic commands ###
