"""piece identity is its starting page

Revision ID: 0741584327eb
Revises: abfe0b42435e
Create Date: 2026-09-03 23:00:09.545128
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0741584327eb'
down_revision = 'abfe0b42435e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Populated table: give the column a default so existing rows can take it,
    # then drop the default so new rows go through the model.  No existing
    # range was set by hand -- there are no page-range-editor candidates in
    # the catalogue -- so false is the truthful backfill.
    op.add_column('piece', sa.Column(
        'pages_confirmed', sa.Boolean(), nullable=False, server_default=sa.false(),
    ))
    op.alter_column('piece', 'pages_confirmed', server_default=None)
    op.drop_index(op.f('ix_piece_file_pages'), table_name='piece')
    op.create_unique_constraint('uq_piece_file_page_start', 'piece', ['source_file_id', 'page_start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_piece_file_page_start', 'piece', type_='unique')
    op.create_index(op.f('ix_piece_file_pages'), 'piece', ['source_file_id', 'page_start'], unique=False)
    op.drop_column('piece', 'pages_confirmed')
    # ### end Alembic commands ###
