"""one annotation layer per page per user

Revision ID: 5006e52258a1
Revises: 95d690531631
Create Date: 2026-09-03 06:16:25.949881
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '5006e52258a1'
down_revision = '95d690531631'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_annotation_page', 'annotation', ['piece_id', 'user_id', 'page'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_annotation_page', 'annotation', type_='unique')
    # ### end Alembic commands ###
