"""musicbrainz title on work

Revision ID: 064aef9c4871
Revises: 4345a58ed002
Create Date: 2026-09-03 18:57:58.050082
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '064aef9c4871'
down_revision = '4345a58ed002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('musicbrainz_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'musicbrainz_title')
    # ### end Alembic commands ###
