"""drop dead schema, enforce one accepted value per field

Revision ID: dcfa020a765c
Revises: ce692cf7da23
Create Date: 2026-09-05 10:47:05.886020
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'dcfa020a765c'
down_revision = 'ce692cf7da23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piece_instrument')
    op.drop_index(op.f('ix_instrument_name'), table_name='instrument')
    op.drop_table('instrument')
    op.create_index('uq_candidate_accepted', 'field_candidate', ['piece_id', 'field'], unique=True, postgresql_where=sa.text('accepted'))
    op.drop_index(op.f('ix_work_parent_work_id'), table_name='work')
    op.drop_constraint(op.f('work_parent_work_id_fkey'), 'work', type_='foreignkey')
    op.drop_column('work', 'parent_work_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('parent_work_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('work_parent_work_id_fkey'), 'work', 'work', ['parent_work_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_work_parent_work_id'), 'work', ['parent_work_id'], unique=False)
    op.drop_index('uq_candidate_accepted', table_name='field_candidate', postgresql_where=sa.text('accepted'))
    op.create_table('instrument',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('instrument_pkey'))
    )
    op.create_index(op.f('ix_instrument_name'), 'instrument', ['name'], unique=True)
    op.create_table('piece_instrument',
    sa.Column('piece_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('piece_instrument_instrument_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], name=op.f('piece_instrument_piece_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('piece_id', 'instrument_id', name=op.f('piece_instrument_pkey'))
    )
    # ### end Alembic commands ###
