"""keep adapter notes on piece

Revision ID: 95d690531631
Revises: 47a819f4520a
Create Date: 2026-09-03 00:51:09.575001
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '95d690531631'
down_revision = '47a819f4520a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The table already holds rows, so the column arrives with a default,
    # is backfilled, and only then becomes NOT NULL.
    op.add_column(
        'piece',
        sa.Column(
            'notes_ingest',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column('piece', 'notes_ingest', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'notes_ingest')
    # ### end Alembic commands ###
