"""composition year on work

Revision ID: 4345a58ed002
Revises: a69c8298eda3
Create Date: 2026-09-03 11:25:08.800312
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4345a58ed002'
down_revision = 'a69c8298eda3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('year_note', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_work_year'), 'work', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_year'), table_name='work')
    op.drop_column('work', 'year_note')
    # ### end Alembic commands ###
