"""sortable catalogue parts on piece

Revision ID: 47a819f4520a
Revises: 996454b654e9
Create Date: 2026-09-03 00:24:31.136430
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '47a819f4520a'
down_revision = '996454b654e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('catalog_system', sa.String(length=12), nullable=True))
    op.add_column('piece', sa.Column('catalog_number', sa.Integer(), nullable=True))
    op.add_column('piece', sa.Column('catalog_suffix', sa.String(length=8), nullable=True))
    op.add_column('piece', sa.Column('catalog_sub', sa.Integer(), nullable=True))
    op.create_index('ix_piece_catalog_sort', 'piece', ['composer_name', 'catalog_system', 'catalog_number', 'catalog_sub'], unique=False)
    op.create_index(op.f('ix_piece_catalog_system'), 'piece', ['catalog_system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_piece_catalog_system'), table_name='piece')
    op.drop_index('ix_piece_catalog_sort', table_name='piece')
    op.drop_column('piece', 'catalog_sub')
    op.drop_column('piece', 'catalog_suffix')
    op.drop_column('piece', 'catalog_number')
    op.drop_column('piece', 'catalog_system')
    # ### end Alembic commands ###
