"""candidate remembers its adapter

Revision ID: abfe0b42435e
Revises: 8aab18d6567c
Create Date: 2026-09-03 19:10:39.221861
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'abfe0b42435e'
down_revision = '8aab18d6567c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_candidate', sa.Column('adapter', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_field_candidate_adapter'), 'field_candidate', ['adapter'], unique=False)

    # Attribute the readings already stored.  Every unaccepted candidate in an
    # existing catalogue came from the scan of its own collection, so the
    # collection's adapter is the reader; accepted ones are decisions and stay
    # unattributed, which is what keeps them out of the adapter's reach.
    op.execute("""
        UPDATE field_candidate AS fc
           SET adapter = c.adapter
          FROM piece AS p
          JOIN source_file AS sf ON sf.id = p.source_file_id
          JOIN collection AS c ON c.id = sf.collection_id
         WHERE fc.piece_id = p.id
           AND fc.accepted IS FALSE
           AND c.adapter IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_candidate_adapter'), table_name='field_candidate')
    op.drop_column('field_candidate', 'adapter')
    # ### end Alembic commands ###
