"""remember deleted page ranges

Revision ID: a69c8298eda3
Revises: 235993d2e507
Create Date: 2026-09-03 08:25:36.605621
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a69c8298eda3'
down_revision = '235993d2e507'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('removed_range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('removed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['removed_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'page_start', 'page_end', name='uq_removed_range')
    )
    op.create_index(op.f('ix_removed_range_source_file_id'), 'removed_range', ['source_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_removed_range_source_file_id'), table_name='removed_range')
    op.drop_table('removed_range')
    # ### end Alembic commands ###
