"""piece movement number

Revision ID: 8aab18d6567c
Revises: 064aef9c4871
Create Date: 2026-09-03 19:05:32.717319
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8aab18d6567c'
down_revision = '064aef9c4871'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('movement', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'movement')
    # ### end Alembic commands ###
